### ISSUE TITLE
Как настроить разные шрифты для разных окон редактора?

### ISSUE THREAD

**Issue by tormozit** [salexdv/bsl_console#194]
В API сейчас для управления всеми шрифтами есть глобальные (для всех окон сразу) настройки
```
setFontSize(size)
setFontFamily(familyName)
```
Но теперь я уже хочу настроить свои параметры для шрифтов
1. Основное окно редактора - ?
2. Окно подсказки автодополнения - monaco-editor .suggest-widget
3. Окно подсказки по вызову метода - editor-widget parameter-hints-widget
4. Окно подсказки удержания указателя - ?

Подозреваю это можно сделать через таблицы стилей.
Я пробовал но не добился успеха
``` bsl
	РедакторHTML = ЭлементФормы.Документ.defaultView;
	ЭлементСтиля = РедакторHTML.document.createElement("style");
	ЭлементСтиля.setAttribute("type", "text/css");
	ЭлементСтиля.innerHTML = "
	// Убираем полосы прокрутки 1С
	|body {
	|	overflow: hidden;
	|	font-size: 13px;
	|	font-family: Lucida Console;
	|}
	// Цвета статусной строки
	|.statusbar-widget {
	|	background: #c2dfef;
	|	color: #000;
	|}
	// Окно подсказки по вызову метода
	|.editor-widget parameter-hints-widget {
	|	font-size: 11px;
	|	font-family: ;
	|}
	// Ширина списка автодополнения
	|.monaco-editor .suggest-widget {
	|	font-size: 11px;
	|	width: 500px;
	|}
	// Ширина списка автодополнения вместе с окном детальной инфы
	|.monaco-editor .suggest-widget.docs-side {
	|	font-size: 11px;
	|	width: 1000px;
	|}
	|";
	РедакторHTML.document.head.appendChild(ЭлементСтиля);
```
Как это правильно сделать?

**Comment by salexdv** [comment]
> Но теперь я уже хочу настроить свои параметры для шрифтов
> 
> 1. Основное окно редактора - ?
> 2. Окно подсказки автодополнения - monaco-editor .suggest-widget
> 3. Окно подсказки по вызову метода - editor-widget parameter-hints-widget
> 4. Окно подсказки удержания указателя - ?
>
> Как это правильно сделать?

1. Для главного окна только так:
```js
setFontSize(size)
setFontFamily(familyName)
```
 2. Окно подсказки автодополнения
 `customOptions: true -> suggestFontSize: xx; suggestLineHeight: yy`

3. Окно подсказки по вызову метода - editor-widget parameter-hints-widget
```css
.editor-widget.parameter-hints-widget .code {
    font-size: XXpx !important;
}
.editor-widget.parameter-hints-widget .docs {
    font-size: XXpx !important;
}
```
4. Окно подсказки удержания указателя
```css
.monaco-editor-hover .hover-row {
    font-size: XXpx !important;
}
```
